name: ğŸ— Laravel CI

on: [pull_request, push]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@7fdd3ece872ec7ec4c098ae5ab7637d5e0a96067
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: ğŸ“‚ Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: ğŸ“¥ Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: ğŸ” Generate key
      run: php artisan key:generate
    - name: ğŸ“‡ Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: ğŸ–¥ Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: ğŸ§ª Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
